server:
  port: 2001

spring:
  application:
    name: eureka-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ehome?serverTimezone=Asia/Shanghai
    username: root
    password: 1qaz2wsx
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 25
      min-idle: 5
      initial-size: 5
      query-timeout: 60
      max-wait: 300000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.entity

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/,http://localhost:1002/eureka/
  instance:
    #每隔5s心跳一次,证明本服务还活着
    lease-renewal-interval-in-seconds: 5
    #本服务10s内没有心跳,就将该服务从服务端剔除
    lease-expiration-duration-in-seconds: 15

# 自定义配置：测试配置管理实时生效的字符串
config:
  auto-update:
    value: "222222222222"
